### ISSUE TITLE
Implement movie detail page

### ISSUE THREAD

**Issue by kuzditomi** [angular-selfstudy-group/show-tarto#11]
We need a movie details page where we can display the movie's:
- title
- release year
- rating
- genre(s)
- plot
- poster image
- backdrop image
- income
- original language
- action buttons: add to favorites, add to watchlist
- make it mobile frienldy

![wp_20170609_16_49_04_pro](https://user-images.githubusercontent.com/3096554/26991885-830aa27e-4d5c-11e7-8d94-0dc6902ad42e.jpg)

**Comment by d4rkpassenger** [comment]
We need a movie details page where we can display the movie:
- title
- release year
- rating
- plot
- cast ( first 5 people in simple list)
- poster image
- backdrop image
- income
- original language
- action buttons: add to favorites, add to watchlist
