### ISSUE TITLE
Implement automated UI tests

### ISSUE THREAD

**Issue by ityu** [angular-selfstudy-group/show-tarto#14]
We need to create automated ui tests for the project.

AC:
- [x] Protractor is set up with the project
- [x] Basic set of smoke test is implemented
- [x] Ways of creating tests and their place in SDLC are described and made clear for all developers

**Comment by kuzditomi** [comment]
Original comment from @ityu:
Startpage test cases:

app-root

 - md-sidenav - hide
 - md-toolbar - show

    - md-input-container - show
    - input placeholder toEqual=Search show
    - input type = Search
    - md icon - Search

  button.mat-icon-button .click = md-sidenav-opened = isDisplayed
**.isPresent()).toBe(true)**
    - nav count = 4
    - nav.first h3.geText = Home
    - nav h3 movies
    - nav h3 series
    - nav.last h3 getText = About

**Comment by ityu** [comment]
Added travis.yml with sample config

**Comment by ityu** [comment]
Run 
`ng e2e`

![show-tart-e2e](https://user-images.githubusercontent.com/1298502/29408700-7f4afa08-8349-11e7-8701-0319fcb8f9dc.JPG)

**Comment by ityu** [comment]
Done and Success:

![show-tart-e2e](https://user-images.githubusercontent.com/1298502/29453658-b8abd90e-840a-11e7-94a5-639dc96bb83f.JPG)
