### ISSUE TITLE
Search result list

### ISSUE THREAD

**Issue by ityu** [angular-selfstudy-group/show-tarto#16]
* design
* no result message

**Comment by d4rkpassenger** [comment]
We need to implement an input text field where the user can type and search for series/movies.

If there is matching titles for the given user input, a drop down list should be shown.
One result (line) In the dropdownlist must contain:
- poster of the movie/series
- title
- release year
- add/remove  favorites button
- add/remove watch list button
- when clicked outside of the buttons a navigation should happen to detail page

If there is no matching titles a notification message should be shown, nearby the input field.
