### ISSUE TITLE
Plan for CI/CD

### ISSUE THREAD

**Issue by d4rkpassenger** [angular-selfstudy-group/show-tarto#21]
Which tools we should use, collect them.

- run unit tests?
- run e2e tests?
- generate coverage report?
- deploy:
-- when
-- what
-- how

**Comment by ityu** [comment]
as I guess
- Protractor - e2e test
- JasmineJS - unit test

**Comment by d4rkpassenger** [comment]
wire into travis CI and Heroku deploy

**Comment by d4rkpassenger** [comment]
lint

**Comment by kuzditomi** [comment]
described in #27
