### ISSUE TITLE
Make the search input and result list mobile friendly

### ISSUE THREAD

**Issue by d4rkpassenger** [angular-selfstudy-group/show-tarto#22]
We need a design for the search input and its results to look nice on mobile devices.

**Comment by ityu** [comment]
## AC:
* Minimal res - Iphone5 compatible ( 320x568 )
* We should handling multiple lines 
(example " Pirates of the Caribbean: The Curse of the Black Pearl ")
* Delete all hover effects, no hiding "Add..." buttons
* Delete Search Icon, unnecessary, the placeholder text I guess enough information.
