### ISSUE TITLE
Kick off CI pipeline

### ISSUE THREAD

**Issue by kuzditomi** [angular-selfstudy-group/show-tarto#27]
We need to set up the contiuous integration for the project. For this, we can use Travis and deploy to Heroku.

AC:
- [x] Travis is building any branch and pull-requests, running unit tests and signals with the results
- [x] Lint is set up ( SytleLint, TypeScript Lint )
- [x] Automated UI test capability is investigated and wired to CI, if possible 
- [x] Slack notification to the channel is set up, if possible
- [x] Firebase account for the project is created and deployment set up from Travis
- [x] Above methods are described and made clear for all developers

**Comment by ityu** [comment]
Added stylintrc and some nre rulo in tslint config files
