### ISSUE TITLE
Implement search for movies / shows

### ISSUE THREAD

**Issue by kuzditomi** [angular-selfstudy-group/show-tarto#5]
![wp_20170609_16_48_27_pro](https://user-images.githubusercontent.com/3096554/26991402-7c205c9e-4d5a-11e7-8466-b00bda923bb9.jpg)
We need a searchbox that show search results from TMDB(?) https://www.themoviedb.org/documentation/api

Please create an account for this and handle the api key some clever way.
Also we must respect their wish to attribute it as the source of data.

**Comment by d4rkpassenger** [comment]
API methods we can use for
- searching (any): https://developers.themoviedb.org/3/search/multi-search
- details:
             - movie: https://developers.themoviedb.org/3/movies/get-movie-details
             - tv: https://developers.themoviedb.org/3/tv/get-tv-details
             - tv-season: https://developers.themoviedb.org/3/tv-seasons/get-tv-season-details
             - tv-episode: https://developers.themoviedb.org/3/tv-episodes/get-tv-episode-details
